services:
  # 1. Ваше Spring Boot приложение (Телеграм-бот и замерщик)
  app:
    build: .
    container_name: keenetic-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - KEENETIC_IP=${KEENETIC_IP}
      - KEENETIC_LOGIN=${KEENETIC_LOGIN}
      - KEENETIC_PASSWORD=${KEENETIC_PASSWORD}
      - TELEGRAM_BOT_NAME=${TELEGRAM_BOT_NAME}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - ADMIN_ID=${ADMIN_ID}
      - TZ=Europe/Moscow
    depends_on:
      - postgres

  # 2. База данных PostgreSQL (Хранение истории метрик 4G сигнала)
  postgres:
    image: postgres:15-alpine
    container_name: keenetic-postgres
    restart: always
    environment:
      TZ: Europe/Moscow
      POSTGRES_DB: keenetic_metrics
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # 3. Grafana (Визуализация и интерактивные графики RSRP / SINR)
  grafana:
    image: grafana/grafana-oss:latest
    container_name: keenetic-grafana
    restart: always
    environment:
      - TZ=Europe/Moscow
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - postgres

  # 4. Jenkins (Локальная система безопасного CI/CD деплоя внутри VDS)
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: keenetic-jenkins
    restart: always
    privileged: true
    user: root
    ports:
      - "9090:8080"
      - "50000:50000"
    environment:
      - JAVA_OPTS=-Xmx1532m
    volumes:
      - jenkins-data:/var/jenkins_home
      - /home/keenetic-controller:/home/keenetic-controller
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/libexec/docker/cli-plugins/docker-compose:/usr/libexec/docker/cli-plugins/docker-compose
    depends_on:
      - postgres

volumes:
  pgdata:
  grafana-data:
  jenkins-data:
