spring:
  datasource:
    url: jdbc:h2:file:~/keenetic_db;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true          # Включает веб-интерфейс консоли
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop # При выключении приложения локальная база будет полностью стираться
    show-sql: true
